version: '3.7'
services:
  postgres:
    image: postgres:12-alpine
    restart: always

    volumes:
      - ./data:/var/lib/postgresql
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: app
      POSTGRES_PASSWORD: 9mREsvXD